name: ci
on: [push]
permissions:
  contents: write
  issues: write
  pull-requests: write
jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Checkout 🛎
        # https://github.com/actions/checkout
        uses: actions/checkout@v4

      - name: Cypress tests
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v6
        with:
          runTests: false

      - name: Tests
        run: npm test

      - name: Semantic Release 🚀
        # https://github.com/cycjimmy/semantic-release-action
        uses: cycjimmy/semantic-release-action@v4
        if: github.ref == 'refs/heads/main'
        with:
          branch: main
        env:
          # github token is automatically created by the GH Action workflow
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # created using semantic-release
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
